### ISSUE TITLE
Magneticraft dusts have no ore dictionary entry

### ISSUE THREAD

**Issue by tommyTT** [superfluke/undiscovered#63]
The dusts that drop from the Magneticraft Sluice Box have no ore dictionary entry assigned to them and therefore can not be used for anything other than smelting into ingots. Maybe this is intentional, but I would rather have no bonus output than having dusts that aren't useful in any crafting recipes (e.g. Magneticraft iron dust cannot be used in the Alloy Kiln to make Invar).

Verified on version 2.3.0 and 2.4.0 of the pack.

Regards,
Tommy

**Comment by superfluke** [comment]
Yes that's intentional. I've considered changing the name/texture of the items to something like metal flakes so players don't think they can use them in recipes like other dusts, but haven't found a texture for that. The bonus dust is the whole point of the sluice for most ores, so not removing that.

**Comment by tommyTT** [comment]
Okay, that‘s a valid choice and a name change would clear that up to avoid confusion. Thanks for the quick reply.
